import = ["~/.config/alacritty/night_owl.toml"]

[env]
term = "xterm-256color"
[window]
decorations = "None"
opacity = 0.7
padding = { x = 5, y = 2 }
dimensions = {columns = 105, lines = 26}

[font]
normal = {family= "VictorMono Nerd Font", style = "Regular"}
bold = {family= "VictorMono Nerd Font", style = "Bold"}
italic = {family= "VictorMono Nerd Font", style = "Italic"}
bold_italic = {family= "VictorMono Nerd Font", style = "Bold Italic"}
size = 12
