[colors.normal]
black = "#555555"
blue = "#8EA7E9"
cyan = "#ACE1AF"
green = "#AAC8A7"
magenta = "#C9BBCF"
red = "#FF9494"
white = "#F7F5EB"
yellow = "#FFD4B2"

[colors.bright]
black = "#555555"
blue = "#E5E0FF"
cyan = "#BFF6C3"
green = "#C3EDC0"
magenta = "#F2D7D9"
red = "#FFB3B3"
white = "#F7F5EB"
yellow = "#FFF6BD"

[colors.primary]
background = "#000000"
foreground = "#f4f4f9"
