import = ["/home/abir/.config/alacritty/themes/tokyo-night.toml", "/home/abir/.config/alacritty/fonts.toml"]
live_config_reload = true
#shell = "/bin/fish"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 105
lines = 25

[window.padding]
x = 7 
y = 7
