[colors.normal]
black = "#555555"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#555555"
blue = "#83a598"
cyan = "#8ec07c"
green = "#bdbb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#bdae93"
yellow = "#fabd2f"

[colors.primary]
background = "#040507"
foreground = "#f4f4f9"
