[font]
size = 17
offset.x = 0
offset.y = 0
glyph_offset = {x = 0, y = 0}

[font.bold]
family = "FiraCode Nerd Font "

[font.bold_italic]
family = "FiraCode Nerd Font "

[font.italic]
family = "FiraCode Nerd Font "

[font.normal]
family = "FiraCode Nerd Font "
