[font]
size = 16
offset.x = 0
offset.y = 0

[font.bold]
family = "VictorMono Nerd Font"

[font.bold_italic]
family = "VictorMono Nerd Font"

[font.italic]
family = "VictorMono Nerd Font"

[font.normal]
family = "VictorMono Nerd Font"
