[font]
size = 18
offset.x = 0
offset.y = -2

[font.bold]
family = "Source Code Pro "

[font.bold_italic]
family = "Source Code Pro "

[font.italic]
family = "Source Code Pro "

[font.normal]
family = "Source Code Pro "
