[font]
size = 18
offset.x = 0
offset.y = -2

[font.bold]
family = "BlexMono Nerd Font "

[font.bold_italic]
family = "BlexMono Nerd Font "

[font.italic]
family = "BlexMono Nerd Font "

[font.normal]
family = "BlexMono Nerd Font "
