#!/bin/bash

# Function to search dotfiles directories with fzf
search_dotfiles() {
  local dotfiles_dirs=("/home/abir/.config" "/home/abir/.local/scripts/")
  local files=()

  # Iterate through each directory and find files, following symlinks
  for dir in "${dotfiles_dirs[@]}"; do
    files+=( $(find -L "$dir" -type f) )
  done

  # Use fzf to select a file
  local selected_file=$(printf "%s\n" "${files[@]}" | fzf) 

  # Check if a file was selected
  if [ -z "$selected_file" ]; then
    echo "No file selected."
    return
  fi

  # Extract directory path from the selected file
  local file_dir=$(dirname "$selected_file")

  # Change directory to the file's directory
  cd "$file_dir"

  # Open the selected file with neovim
  nvim "$selected_file" 
}

# Call the search_dotfiles function
search_dotfiles
