format = """
[](#1e1e2e)\
$python\
$username\
[](bg:#1e1e2e fg:#1e1e2e)\
$directory\
[](fg:#1e1e2e bg:#585b70)\
$git_branch\
$git_status\
[](fg:#585b70 bg:#89b4fa)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#89b4fa bg:#94e2d5)\
$docker_context\
[](fg:#94e2d5 bg:#f5e2f7)\
$time\
[ ](fg:#f5e2f7)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#1e1e2e"
style_root = "bg:#1e1e2e"
format = '[$user ]($style)'

[directory]
style = "bg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#585b70"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#585b70"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#1e1e2e"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#89b4fa"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#f5e2f7 fg:#1e1e2e"
format = '[ $time ]($style)'
