[theme]
theme = "slick"

[[block]]
block = "pacman"
signal = 1
interval = 600
format = "  $pacman updates available "
format_singular = "  $pacman update available "
format_up_to_date = "  system up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
[[block.click]]
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs-$USER/ | rofi -show dmenu"
[[block.click]]
# Updates the block on right click
button = "right"
update = true
[[block]]
block = "cpu"
interval = 1
format = "  $utilization "
[[block]]
block = "memory"
format = "  $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90
[[block]]
block = "battery"
format = "  $percentage "
full_format = ""
empty_format = ""
charging_format = ""
device = "DisplayDevice"
driver = "upower"
