[colors.normal]
black = "#191d24"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#d8dee9"
yellow = "#ebcb8b"

[colors.bright]
black = "#3b4252"
blue = "#88c0d0"
cyan = "#93ccdc"
green = "#b1d196"
magenta = "#c895bf"
red = "#d06f79"
white = "#e5e9f0"
yellow = "#f0d399"

[colors.primary]
# background = "#242933"
background = "#212121"
foreground = "#d8dee9"
