#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") fin="󱊦 " ;;
		"Discharging") status="d" ;;
		"Charging") fin="🔌 " ;;
		"Not charging") fin="󰏝 " ;;
		"Unknown") fin="󰂑 " ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "d" ] && fin="  "
	[ "$status" = "d" ] && [ "$capacity" -le 75 ] && fin="  "
	[ "$status" = "d" ] && [ "$capacity" -le 50 ] && fin="  "
	[ "$status" = "d" ] && [ "$capacity" -le 33 ] && fin="  "
	[ "$status" = "d" ] && [ "$capacity" -le 12 ] && warn="❗ "
	# Prints the info
	printf "%s%s%d%%" "$fin" "$warn" "$capacity"; unset warn
done && printf "\\n"
